In [1]:
import numpy as np

data=np.random.randn(2,3)
data


array([[ 0.48232819,  0.96886741, -0.49761439],
       [-1.39591507, -0.81607119,  0.28864691]])

In [2]:
data*10


array([[  4.8232819 ,   9.6886741 ,  -4.97614387],
       [-13.9591507 ,  -8.16071187,   2.88646908]])

In [3]:
data+data

array([[ 0.96465638,  1.93773482, -0.99522877],
       [-2.79183014, -1.63214237,  0.57729382]])

# shape dtype

In [5]:
data.dtype

dtype('float64')

In [6]:
data.shape


(2, 3)

# 创建ndarray

In [7]:
data1=[6,7.5,8, 0, 1]
arr1=np.array(data1)

arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [8]:
data2=[[1, 3,4,5],
       [3, 4,3,3] ]
arr2=np.array(data2)

arr2

array([[1, 3, 4, 5],
       [3, 4, 3, 3]])

# ndim shape dtype

In [9]:
arr2.ndim

2

In [10]:
arr2.shape

(2, 4)

In [11]:
arr1.dtype

dtype('float64')

In [12]:
arr2.dtype

dtype('int32')

# np.zeros np.ones np.empty

In [13]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [16]:
np.zeros((3,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [138]:
np.empty((2,2))
#接近于零的矩阵

array([[2.12199579e-314, 6.36598737e-314],
       [1.06099790e-313, 1.48539705e-313]])

In [35]:
np.ones((2,4),dtype=np.float32)

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)

# arange

In [21]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [23]:
np.arange(8,15,2)

array([ 8, 10, 12, 14])

# 对角阵的创建

In [32]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# ndarray数据类型

查看数据类型 array.dtype

In [34]:
arr1=np.array([1, 3, 5],dtype=np.float64)
arr1

array([1., 3., 5.])

In [36]:
arr1.dtype

dtype('float64')

修改数据类型 array.astype

In [40]:
arr=np.random.randn(3,3)
arr.dtype

dtype('float64')

In [41]:
arr.astype(np.float32)

array([[ 0.36296317, -0.30304703,  0.67669964],
       [-0.34216347,  0.01486249, -0.93386513],
       [ 0.33943424, -0.34463048,  0.27621776]], dtype=float32)

In [42]:
arr.astype(np.int32)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [46]:
numeri_strings=np.array(['1.25', '3.33', '5.55'],
                        dtype=np.string_)
numeri_strings.astype(float)

array([1.25, 3.33, 5.55])

In [48]:
int_array=np.arange(10)
calibers=np.array([.22, .33, .44, .555],
                  dtype=np.float64)
int_array.astype(calibers.dtype)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

# numpy数组的运算

In [49]:
arr=np.array([[2, 2, 5],
            [3, 4, 7]])
arr

array([[2, 2, 5],
       [3, 4, 7]])

In [50]:
arr*arr

array([[ 4,  4, 25],
       [ 9, 16, 49]])

In [51]:
arr-arr

array([[0, 0, 0],
       [0, 0, 0]])

In [52]:
1/arr

array([[0.5       , 0.5       , 0.2       ],
       [0.33333333, 0.25      , 0.14285714]])

In [53]:
arr**2

array([[ 4,  4, 25],
       [ 9, 16, 49]], dtype=int32)

In [54]:
arr1=([[2,2,9],
      [5,5,4]])
arr>arr1

array([[False, False, False],
       [False, False,  True]])

# 基本的索引和切片

In [56]:
arr=np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [57]:
arr[5]

5

In [58]:
arr[5:9]

array([5, 6, 7, 8])

In [61]:
arr[3:5]=0
arr

array([0, 1, 2, 0, 0, 5, 6, 7, 8, 9])

In [64]:
arr_slice=arr[3:5]
arr_slice

array([0, 0])

In [65]:
arr_slice[1]=12345
arr

array([    0,     1,     2,     0, 12345,     5,     6,     7,     8,
           9])

In [69]:
arr3=np.array([[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]])
arr3[2]
arr3.shape

(3, 3)

In [68]:
arr3[2][1]

8

In [70]:
old=arr3[2].copy()
arr3[2]=15
arr3

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [15, 15, 15]])

In [71]:
arr3[2]=old
arr3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# 切片索引

In [72]:
arr

array([    0,     1,     2,     0, 12345,     5,     6,     7,     8,
           9])

In [73]:
arr[1:6]

array([    1,     2,     0, 12345,     5])

In [76]:
arr3[:2]
arr3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [77]:
arr3[:2,1:]

array([[2, 3],
       [5, 6]])

In [79]:
arr3[0,0]

1

# 布尔型索引

In [80]:
names=np.array(['Bob','Joe','Will', 'Bob','Will',
                'Joe','Joe'])
data=np.random.randn(7,4)
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [81]:
data

array([[ 0.20755847, -1.15807763, -0.18881268, -1.17265074],
       [-1.04168886, -0.87678303, -1.34376195,  0.19088975],
       [-0.36757895,  0.44635683, -0.26579016, -0.4256675 ],
       [-0.04957984, -0.30041408,  0.70676151,  0.11965801],
       [ 0.02262883, -1.88469171, -1.1011253 , -1.03807896],
       [ 0.20217377,  0.1091494 ,  0.56467273,  0.8114897 ],
       [-1.86671999, -0.01405595, -0.16798401, -0.71699868]])

In [83]:
names=="Bob"

array([ True, False, False,  True, False, False, False])

In [84]:
data[names=="Joe"]

array([[-1.04168886, -0.87678303, -1.34376195,  0.19088975],
       [ 0.20217377,  0.1091494 ,  0.56467273,  0.8114897 ],
       [-1.86671999, -0.01405595, -0.16798401, -0.71699868]])

In [86]:
cond=names=="Joe"
data[~cond]

array([[ 0.20755847, -1.15807763, -0.18881268, -1.17265074],
       [-0.36757895,  0.44635683, -0.26579016, -0.4256675 ],
       [-0.04957984, -0.30041408,  0.70676151,  0.11965801],
       [ 0.02262883, -1.88469171, -1.1011253 , -1.03807896]])

# 布尔条件 &（和）|（或）

In [87]:
cond=(names=="Joe")|(names=="Bob")
data[cond]

array([[ 0.20755847, -1.15807763, -0.18881268, -1.17265074],
       [-1.04168886, -0.87678303, -1.34376195,  0.19088975],
       [-0.04957984, -0.30041408,  0.70676151,  0.11965801],
       [ 0.20217377,  0.1091494 ,  0.56467273,  0.8114897 ],
       [-1.86671999, -0.01405595, -0.16798401, -0.71699868]])

In [88]:
data[data<0]=0
data

array([[0.20755847, 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.19088975],
       [0.        , 0.44635683, 0.        , 0.        ],
       [0.        , 0.        , 0.70676151, 0.11965801],
       [0.02262883, 0.        , 0.        , 0.        ],
       [0.20217377, 0.1091494 , 0.56467273, 0.8114897 ],
       [0.        , 0.        , 0.        , 0.        ]])


# 花式索引

花式索引是指利用整数数组进行索引

In [90]:
arr=np.empty((8,4))

for i in range(8):
    arr[i]=i
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [92]:
arr[[4, 3, 0, 6]]

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

In [94]:
arr[[-1, -2, -5]]

array([[7., 7., 7., 7.],
       [6., 6., 6., 6.],
       [3., 3., 3., 3.]])

In [95]:
arr=np.arange(32).reshape(8,4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

# 数组转置和轴对换

In [101]:
arr=np.arange(15).reshape(3,5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

arr.T 矩阵转置

In [98]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [100]:
arr=np.random.randn(6,3)
arr

array([[-1.34489549, -0.38709551, -0.49139365],
       [ 0.18138048, -1.12526477,  0.63826959],
       [ 0.27220583, -0.43950512,  1.13816155],
       [ 1.82698405, -2.0514648 ,  0.65731118],
       [-0.07954501, -0.18402199,  1.1417803 ],
       [ 1.24868389, -1.42894108,  1.56412528]])

np.dot()矩阵内积

In [102]:
np.dot(arr.T,arr)

array([[125, 140, 155, 170, 185],
       [140, 158, 176, 194, 212],
       [155, 176, 197, 218, 239],
       [170, 194, 218, 242, 266],
       [185, 212, 239, 266, 293]])

In [106]:
arr=np.arange(16).reshape(2,2,4)
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

transpose

In [115]:
arr.transpose((1,0,2))

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

# 4.2 通用函数：快速的元素级数组成数

#通用函数ufunc是一种对ndarray中的数据执行元素级运算的函数

In [117]:
arr=np.arange(9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [118]:
np.sqrt(arr)

array([[0.        , 1.        , 1.41421356],
       [1.73205081, 2.        , 2.23606798],
       [2.44948974, 2.64575131, 2.82842712]])

In [119]:
np.exp(arr)

array([[1.00000000e+00, 2.71828183e+00, 7.38905610e+00],
       [2.00855369e+01, 5.45981500e+01, 1.48413159e+02],
       [4.03428793e+02, 1.09663316e+03, 2.98095799e+03]])

In [121]:
x=np.random.randn(9)
y=np.random.randn(9)

np.maximum(x,y)

array([0.19636949, 0.20507296, 0.72858932, 0.94726355, 1.37175876,
       1.73541454, 0.448085  , 0.52561751, 0.27341598])

In [123]:
arr=x*5
arr

array([-4.51147373,  1.02536478,  3.64294661,  4.73631776,  6.85879379,
        8.67707271,  0.48352534, -0.89676231,  1.36707988])

# 一元ufunc

abs 绝对值

sqrt平方根

square
exp 计算指数
log log10 log2 log1p
sign 计算各元素的正负号
ceil(计算各元素的ceiling值，即大于等于该值的最小整数)
floor（计算各元素的floor值，即小于等于该值的最大整数）

# 二元ufunc

In [125]:
arr1=np.random.randn(4,4)
arr2=np.random.randn(4,4)
arr1

array([[-1.6457303 ,  0.31395936, -0.97107446, -0.83195868],
       [-1.84983856, -0.39008105,  0.55155288,  0.67512054],
       [-0.14476494, -0.89325745, -1.70567169,  0.31815635],
       [ 0.59175712, -0.99366137,  1.56558935,  0.30561315]])

In [131]:
np.add(arr1,arr2)

array([[-1.09910432, -0.54644207, -3.18902124,  0.17991961],
       [-0.83658651, -0.97257311,  0.4388471 ,  1.3175753 ],
       [ 0.30606976,  0.34969378, -1.62332796,  0.38003057],
       [ 2.34417257, -0.96481504,  1.5585233 ,  0.05635675]])

In [132]:
np.subtract(arr1,arr2)

array([[-2.19235627,  1.1743608 ,  1.24687231, -1.84383697],
       [-2.86309061,  0.19241101,  0.66425866,  0.03266577],
       [-0.59559964, -2.13620867, -1.78801542,  0.25628213],
       [-1.16065833, -1.02250769,  1.5726554 ,  0.55486955]])

In [133]:
np.multiply(arr1,arr2)

array([[-0.89959893, -0.27013109,  2.15379147, -0.84184093],
       [-1.87435272,  0.22721911, -0.0621632 ,  0.43373441],
       [-0.06526506, -1.11027544, -0.14045137,  0.01968568],
       [ 1.03700432, -0.02866348, -0.01106253, -0.07617603]])

In [137]:
np.divide(arr1,arr2)
np.floor_divide(arr1,arr2)
np.fmax(arr1,arr2)

array([[ 0.54662597,  0.31395936, -0.97107446,  1.01187829],
       [ 1.01325205, -0.39008105,  0.55155288,  0.67512054],
       [ 0.4508347 ,  1.24295122,  0.08234373,  0.31815635],
       [ 1.75241545,  0.02884632,  1.56558935,  0.30561315]])

# 4.3 利用数组进行数据处理

用数组表达式代替循环的做法，通常被成为矢量化

np.meshgrid()接受两个一维数组，并产生两个二位矩阵，对应两个数组中所有的（x,y）对

In [139]:
points=np.arange(-5, 5, 0.1)
xs,ys= np.meshgrid(points, points)
ys

array([[-5. , -5. , -5. , ..., -5. , -5. , -5. ],
       [-4.9, -4.9, -4.9, ..., -4.9, -4.9, -4.9],
       [-4.8, -4.8, -4.8, ..., -4.8, -4.8, -4.8],
       ...,
       [ 4.7,  4.7,  4.7, ...,  4.7,  4.7,  4.7],
       [ 4.8,  4.8,  4.8, ...,  4.8,  4.8,  4.8],
       [ 4.9,  4.9,  4.9, ...,  4.9,  4.9,  4.9]])

In [ ]:
z=np.sqrt(xs**2+ys**2)
z

# matplotlib 二维数组可视化

In [141]:
import matplotlib.pyplot as plt
plt.imshow(z, cmap=plt.cm.gray);plt.colorbar

<function matplotlib.pyplot.colorbar(mappable=None, cax=None, ax=None, **kw)>

# 将条件逻辑表述为数组运算

## numpy.where

In [142]:
xarr=np.array([1.1, 1.2 ,1.3, 1.4, 1.5])
yarr=np.array([2.1, 2.2, 2.3, 2.4, 2.5])
cond=np.array([True, False, True,  True, False])
result=[(x if c else y)
       for x, y, c in zip(xarr, yarr,cond)]
result

[1.1, 2.2, 1.3, 1.4, 2.5]

In [143]:
result=np.where(cond, xarr, yarr)
result

array([1.1, 2.2, 1.3, 1.4, 2.5])

In [144]:
arr=np.random.randn(4,4)
arr

array([[-1.25933004, -0.52219153,  0.64237595, -0.24486846],
       [ 2.30226256,  0.78500603,  2.96194474,  1.82031566],
       [ 1.3437984 ,  0.63646361,  1.48510581,  1.79912938],
       [-0.10566234, -1.27156355, -0.91802934,  2.13316558]])

In [145]:
arr>0

array([[False, False,  True, False],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [False, False, False,  True]])

In [146]:
np.where(arr>0,2,-2)

array([[-2, -2,  2, -2],
       [ 2,  2,  2,  2],
       [ 2,  2,  2,  2],
       [-2, -2, -2,  2]])

In [147]:
np.where(arr>0, 2, arr)

array([[-1.25933004, -0.52219153,  2.        , -0.24486846],
       [ 2.        ,  2.        ,  2.        ,  2.        ],
       [ 2.        ,  2.        ,  2.        ,  2.        ],
       [-0.10566234, -1.27156355, -0.91802934,  2.        ]])

## 数学和统计方法

可以通过数组上一组数学函数对整个数组或某个轴向的数据进行统计计算。
sum, mean ,以及标准差std等聚合计算。

axis=0 列
axis=1 行

In [149]:
arr=np.random.randn(5,4)
arr

array([[-1.29487584,  0.541404  , -0.23802631,  1.82286747],
       [-1.28977451, -1.91700251,  0.19872554,  0.35105055],
       [-0.88096015,  0.6835561 , -0.12131957,  0.03881758],
       [-0.62972158, -1.08736284,  0.76581319, -1.30698724],
       [-0.37376672, -0.30279055, -2.64253973,  0.53682268]])

In [150]:
arr.mean()

-0.3573035214323373

In [152]:
np.mean(arr)

-0.3573035214323373

In [153]:
arr.sum()

-7.146070428646746

In [154]:
arr.mean(axis=1)

array([ 0.20784233, -0.66425023, -0.06997651, -0.56456462, -0.69556858])

In [155]:
arr.mean(axis=0)

array([-0.89381976, -0.41643916, -0.40746937,  0.28851421])

In [158]:
t=arr.T
t

array([[-1.29487584, -1.28977451, -0.88096015, -0.62972158, -0.37376672],
       [ 0.541404  , -1.91700251,  0.6835561 , -1.08736284, -0.30279055],
       [-0.23802631,  0.19872554, -0.12131957,  0.76581319, -2.64253973],
       [ 1.82286747,  0.35105055,  0.03881758, -1.30698724,  0.53682268]])

In [159]:
t.mean(axis=1)

array([-0.89381976, -0.41643916, -0.40746937,  0.28851421])

In [160]:
t.mean(axis=0)

array([ 0.20784233, -0.66425023, -0.06997651, -0.56456462, -0.69556858])

In [161]:
arr.sum(0)

array([-4.4690988 , -2.0821958 , -2.03734687,  1.44257104])

In [162]:
arr.std()

1.0230564338628056

In [163]:
arr.min(0)

array([-1.29487584, -1.91700251, -2.64253973, -1.30698724])

In [4]:
import numpy as np
arr=np.random.random(5)
arr.argmin(0)
#每一行的最小值的索引位置

2

In [6]:
print(arr)
np.cumsum(arr)

# 累加

[0.2843986  0.66548386 0.18916095 0.74424634 0.25240465]


array([0.2843986 , 0.94988246, 1.1390434 , 1.88328975, 2.1356944 ])

In [7]:
print(np.diff(arr))

[ 0.38108525 -0.47632291  0.55508539 -0.49184169]


In [13]:
print(np.nonzero(arr))

# 找出非零元素的位置索引
np.info(np.nonzero)

(array([0, 1, 2, 3, 4], dtype=int64),)
 nonzero(a)

Return the indices of the elements that are non-zero.

Returns a tuple of arrays, one for each dimension of `a`,
containing the indices of the non-zero elements in that
dimension. The values in `a` are always tested and returned in
row-major, C-style order. The corresponding non-zero
values can be obtained with::

    a[nonzero(a)]

To group the indices by element, rather than dimension, use::

    transpose(nonzero(a))

The result of this is always a 2-D array, with a row for
each non-zero element.

Parameters
----------
a : array_like
    Input array.

Returns
-------
tuple_of_arrays : tuple
    Indices of elements that are non-zero.

See Also
--------
flatnonzero :
    Return indices that are non-zero in the flattened version of the input
    array.
ndarray.nonzero :
    Equivalent ndarray method.
count_nonzero :
    Counts the number of non-zero elements in the input array.

Examples
--------
>>> x = np.array([[3, 0, 0], [0, 4, 0]

### np.mean(arr,axis=0)

### np.max(arr,axis=1)

### np.min(arr)

axis=0 行
axis=1 列

## 用于布尔型数组的方法

In [166]:
arr=np.random.randn(4,4)
arr

array([[ 1.15625388,  1.10759923, -2.00517197, -0.44585552],
       [-1.58690642,  0.23274518,  0.08600334, -0.53572278],
       [-0.35783207, -0.40040413, -0.76976088,  0.28409334],
       [-0.23384324, -0.99502289, -0.81435654, -0.67412035]])

In [167]:
(arr> 0).sum()

5

In [169]:
bools=arr>0

In [170]:
bools.any()
#用于测试数组中是否存在一个或多个True

True

In [171]:
bools.all()
#用于测试数组中所有值是否都为True

False

## 排序

In [ ]:
### 知识总结：



In [173]:
arr=np.random.randn(6)
arr

array([ 1.32752414,  0.6232193 ,  0.31013167,  0.01314966,  0.72323903,
       -0.55909979])

In [175]:
arr.sort()
arr

array([-0.55909979,  0.01314966,  0.31013167,  0.6232193 ,  0.72323903,
        1.32752414])

In [176]:
arr=np.random.randn(5,3)
arr

array([[-1.20660322, -0.65446065, -0.54867542],
       [-0.41907115, -1.11235388,  1.4140805 ],
       [ 0.10570194,  0.4178044 , -1.89038302],
       [ 2.12204415,  0.58104171, -1.3449951 ],
       [ 0.34193965, -0.76398108, -0.7344797 ]])

In [177]:
arr.sort(1)
arr

array([[-1.20660322, -0.65446065, -0.54867542],
       [-1.11235388, -0.41907115,  1.4140805 ],
       [-1.89038302,  0.10570194,  0.4178044 ],
       [-1.3449951 ,  0.58104171,  2.12204415],
       [-0.76398108, -0.7344797 ,  0.34193965]])

In [179]:
old_arr=np.random.randn(100)
old_arr.sort()
old_arr[int(0.5*len(old_arr))]

0.1974736612991989

## 唯一化以及其他的集合逻辑

### np.unique()

用于找出数组中的唯一值，并返回已经排序的结构

In [180]:
names=np.array(['Bob','Joe', 'Will', 'Bob','Will',
                'Joe', 'Joe'])
np.unique(names)

array(['Bob', 'Joe', 'Will'], dtype='<U4')

In [181]:
ints=np.array([3,3,3, 2,2,2, 1,1,1, 4,4,4,])
np.unique(ints)

array([1, 2, 3, 4])

In [182]:
sorted(set(names))

['Bob', 'Joe', 'Will']

### np.in1d(arr1,arr2)

用来测试一个数组中的值在另一个数组中的成员资格，返回一个布尔型数组


In [185]:
values= np.array([6, 0, 0, 3,2, 5, 6])
np.in1d(values,[2, 3, 6])

array([ True, False, False,  True,  True, False,  True])

np.unique()

intersect1d(x,y) 
#用于计算x,y中的公共元素（交集），并返回有序结果

union1d(x,y)
#用于计算x,y的并集，且返回有序结果

In [187]:
x=np.arange(10)
y=np.arange(15)

In [189]:
np.intersect1d(x,y)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [190]:
np.union1d(x,y)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [191]:
np.in1d(y,x)

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False, False, False, False, False])

In [193]:
np.setdiff1d(y,x)

array([10, 11, 12, 13, 14])

In [194]:
np.setxor1d(x,y)

array([10, 11, 12, 13, 14])

# 4.4 用于数组的文件输入输出

np.save

np.load

# 4.5 线性代数

### 矩阵乘法 x.dot(y)  np.dot(x,y)

In [196]:
x=np.array([[1, 2, 3],[4, 5, 6]])
y=np.array([[6, 23],[-1, 7],[8, 9]])
x.dot(y)

array([[ 28,  64],
       [ 67, 181]])

In [197]:
x.shape

(2, 3)

In [198]:
y.shape

(3, 2)

In [199]:
np.dot(x,y)

array([[ 28,  64],
       [ 67, 181]])

In [201]:
from numpy.linalg import inv, qr
x=np.random.randn(5,5)
mat=x.T.dot(x)
inv(mat)

array([[ 11.9389992 ,  10.5223663 ,   6.71993931,   0.42880424,
        -11.6063417 ],
       [ 10.5223663 ,   9.44399446,   5.94107594,   0.47730544,
        -10.21703523],
       [  6.71993931,   5.94107594,   4.00769776,   0.19279449,
         -6.58488852],
       [  0.42880424,   0.47730544,   0.19279449,   1.16922764,
          0.23263342],
       [-11.6063417 , -10.21703523,  -6.58488852,   0.23263342,
         11.91389355]])

In [208]:
arr=mat.dot(inv(mat))
arr

array([[ 1.00000000e+00,  5.44412066e-15,  4.81044323e-15,
         1.37069625e-16, -9.07923830e-16],
       [ 1.89534615e-14,  1.00000000e+00,  1.64060774e-15,
        -7.54048152e-17, -1.04372278e-16],
       [ 5.60191653e-16, -7.95962806e-16,  1.00000000e+00,
        -1.44607186e-17, -9.23589682e-16],
       [-9.83346814e-16, -5.07704600e-16, -6.89537729e-16,
         1.00000000e+00,  1.93821546e-15],
       [-1.51402636e-17,  1.36802948e-15,  1.74967354e-15,
         2.18726544e-17,  1.00000000e+00]])

In [211]:
q,r =qr(mat)
r

array([[-9.6448109 ,  5.99448269,  1.9125266 ,  1.53958515, -3.25289078],
       [ 0.        , -5.39495449,  1.76266661,  2.97414357, -3.75392682],
       [ 0.        ,  0.        , -4.20250752,  1.34328378, -2.3852484 ],
       [ 0.        ,  0.        ,  0.        , -0.76331835, -0.01452983],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.0485385 ]])

# 常用的numpy.linalg函数

In [213]:
arr1=np.random.randn(5,5)
arr2=np.random.randn(5,2)
np.dot(arr1,arr2)

array([[ 3.10753989, -0.49527897],
       [-1.1993625 , -1.18731895],
       [-1.43739987, -0.32442358],
       [ 0.51913413, -3.11357943],
       [ 1.72164442,  2.43612304]])

diag

trace 计算对角线元素的和

det 计算矩阵行列式

eig 计算方阵的本征值和本征向量

inv 计算方阵的逆

pinv

qr 计算QR分解

svd

solve

Istsp

# 4.6伪随机数生成

In [216]:
samples=np.random.normal(size=(4,4))
samples

array([[ 0.13887177, -0.8558008 , -0.12144623, -1.02646012],
       [ 0.68246253,  2.37422304, -1.48825281, -0.02735279],
       [ 1.84709411, -0.19460526, -1.67496677, -1.81221936],
       [ 0.42025421,  0.98185627,  2.13499021, -0.99311085]])

In [ ]:
from random import normalvariate
N= 1000


## numpy.random函数

seed

permutation

shuffle

rand 

randint

randn

binomial

normal

beta

chisquare

gamma

uniform

# 4.7 随机漫步

In [ ]:
import random
